### ISSUE TITLE
Where is this project code?

### ISSUE THREAD

**Issue by ghost** [fedor4ever/SDL_Player#1]
References:
* https://github.com/search?utf8=%E2%9C%93&q=sdl%20player&ref=simplesearch&s=updated
  * https://github.com/xieaoran/SDLPlayer
  * https://github.com/cocafe/Simple_FFmpeg_SDL_Audio_Player
  * ...

**Comment by fedor4ever** [comment]
https://github.com/fedor4ever/SDL_Player/wiki
I will glad if you fix because that project doesn't work. It allocate memory more than 30mb ram, freezes and exit. Contact with me via sourceforge pm. See at ffmeg symbian port.
Fiodar Stryzhniou

исходное сбщ
Тема: [fedor4ever/SDL_Player] Where is this project code? (#1)
От: AppSoft4 <notifications@github.com>
Дата: 29.03.2017 23.52



-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/fedor4ever/SDL_Player/issues/1
